version: '3.8'

services:
  microservicio.intermedio:
    image: ${DOCKER_REGISTRY-}microserviciointermedio
    build:
      context: .
      dockerfile: Taller/Taller.WebApi/Dockerfile
      shm_size: '1gb'
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1434:1433"
    environment:
        SA_PASSWORD: "Passw0rd123"
        MSSQL_PID: Developer
        ACCEPT_EULA: "Y"
